services:
  frontend:
    build:
      context: ./url-analyzer-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./url-analyzer-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - url-analyzer-network
    depends_on:
      - backend

  backend:
    build:
      context: ./url-analyzer-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=url_analyzer
      - API_KEY=your-secure-api-key-here
      - PORT=8000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - url-analyzer-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=url_analyzer
    volumes:
      - mysql_data:/var/lib/mysql
      - ./url-analyzer-backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - url-analyzer-network

volumes:
  mysql_data:

networks:
  url-analyzer-network:
    driver: bridge
