version: "3.9"

services:
  frontend:
    build:
      context: ./url-analyzer-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - url-analyzer-network

  backend:
    build:
      context: ./url-analyzer-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=url_analyzer
      - API_KEY=test-api-key-12345
      - PORT=8000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - url-analyzer-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=url_analyzer
    volumes:
      - mysql_data:/var/lib/mysql
      - ./url-analyzer-backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - url-analyzer-network

volumes:
  mysql_data:

networks:
  url-analyzer-network:
    driver: bridge