services:
  - type: web
    name: url-analyzer-backend
    env: docker
    plan: free
    dockerfilePath: ./url-analyzer-backend/Dockerfile
    dockerContext: ./url-analyzer-backend
    envVars:
      - key: DB_HOST
        value: url-analyzer-mysql
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: rootpassword
      - key: DB_NAME
        value: url_analyzer
      - key: API_KEY
        value: test-api-key-12345
      - key: PORT
        value: 8000
    healthCheckPath: /api/health

  - type: web
    name: url-analyzer-frontend
    env: docker
    plan: free
    dockerfilePath: ./url-analyzer-frontend/Dockerfile
    dockerContext: ./url-analyzer-frontend
    envVars:
      - key: VITE_API_URL
        value: https://url-analyzer-backend.onrender.com/api
    buildFilter:
      paths:
        - url-analyzer-frontend/**
  
databases:
  - name: url-analyzer-mysql
    plan: free
    databaseName: url_analyzer
    user: root