basePath: /api
definitions:
  internal_handlers.DeleteURLsRequest:
    properties:
      ids:
        items:
          type: integer
        minItems: 1
        type: array
    required:
    - ids
    type: object
  url-analyzer_internal_models.CreateURLRequest:
    properties:
      url:
        type: string
    required:
    - url
    type: object
  url-analyzer_internal_models.PaginatedResponse:
    properties:
      data: {}
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A web application that accepts website URLs, crawls them and displays
    key information about the pages.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: URL Analyzer API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Get the health status of the API and its dependencies
      produces:
      - application/json
      responses:
        "200":
          description: System is healthy
          schema:
            additionalProperties: true
            type: object
        "503":
          description: System is unhealthy
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - System
  /jobs:
    get:
      description: Returns a list of currently active crawl jobs
      produces:
      - application/json
      responses:
        "200":
          description: Active jobs
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get active crawl jobs
      tags:
      - System
  /jobs/cleanup:
    post:
      description: Cleans up completed or stale jobs from the system
      produces:
      - application/json
      responses:
        "200":
          description: Jobs cleaned up successfully
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to clean up jobs
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Clean up old/finished jobs
      tags:
      - System
  /stats:
    get:
      consumes:
      - application/json
      description: Get detailed statistics about the system, database, and crawler
      produces:
      - application/json
      responses:
        "200":
          description: System statistics
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get system statistics
      tags:
      - System
  /urls:
    delete:
      consumes:
      - application/json
      description: Delete multiple URLs by their IDs
      parameters:
      - description: List of URL IDs to delete
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.DeleteURLsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: URLs deleted successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request format
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Delete multiple URLs
      tags:
      - URLs
    get:
      consumes:
      - application/json
      description: Get a paginated list of URLs with optional filtering and sorting
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: page_size
        type: integer
      - description: Filter by status
        enum:
        - queued
        - running
        - completed
        - error
        in: query
        name: status
        type: string
      - description: Search in URL or title
        in: query
        name: search
        type: string
      - default: created_at
        description: Sort field
        in: query
        name: sort_by
        type: string
      - default: desc
        description: Sort order
        enum:
        - asc
        - desc
        in: query
        name: sort_order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of URLs
          schema:
            $ref: '#/definitions/url-analyzer_internal_models.PaginatedResponse'
        "400":
          description: Invalid query parameters
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: List URLs with pagination and filtering
      tags:
      - URLs
    post:
      consumes:
      - application/json
      description: Add a new URL to be crawled and analyzed
      parameters:
      - description: URL to add
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/url-analyzer_internal_models.CreateURLRequest'
      produces:
      - application/json
      responses:
        "201":
          description: URL added successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request format
          schema:
            additionalProperties: true
            type: object
        "409":
          description: URL already exists
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Add a new URL for analysis
      tags:
      - URLs
  /urls/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a specific URL and all its associated data
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: URL deleted successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid URL ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: URL not found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Delete a URL
      tags:
      - URLs
    get:
      consumes:
      - application/json
      description: Get detailed information about a specific URL including crawl results
        and broken links
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: URL details with crawl results
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid URL ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: URL not found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get detailed information about a URL
      tags:
      - URLs
  /urls/{id}/restart:
    put:
      consumes:
      - application/json
      description: Restart the crawling process for a specific URL
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Crawl restarted successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid URL ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: URL not found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Restart a crawl for a URL
      tags:
      - Crawl Control
  /urls/{id}/start:
    put:
      consumes:
      - application/json
      description: Start the crawling process for a specific URL
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Crawl started successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid URL ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: URL not found
          schema:
            additionalProperties: true
            type: object
        "409":
          description: Crawl already in progress
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Start crawling a URL
      tags:
      - Crawl Control
  /urls/{id}/status:
    get:
      consumes:
      - application/json
      description: Get the current status of a crawl job for a specific URL
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Crawl job status
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid URL ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: No active crawl job found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get the status of a crawl job
      tags:
      - Crawl Control
  /urls/{id}/stop:
    put:
      consumes:
      - application/json
      description: Stop the crawling process for a specific URL
      parameters:
      - description: URL ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Crawl stopped successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid URL ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: No active crawl job found
          schema:
            additionalProperties: true
            type: object
        "409":
          description: Crawl job already finished
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Stop crawling a URL
      tags:
      - Crawl Control
securityDefinitions:
  ApiKeyAuth:
    description: 'Enter your API key in the format: test-api-key-12345'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
