services:
  # Database
  mysql:
    image: mysql:8.0
    container_name: url_analyzer_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: url_analyzer
      MYSQL_USER: analyzer_user
      MYSQL_PASSWORD: analyzer_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
      interval: 10s

  # API Server
  api:
    build: .
    container_name: url_analyzer_api
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=url_analyzer
      - DB_USER=analyzer_user
      - DB_PASSWORD=analyzer_password
      - SERVER_PORT=8000
      - SERVER_HOST=0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  # Database Admin Interface
  adminer:
    image: adminer:4.8.1
    container_name: url_analyzer_adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql_data: